### ISSUE TITLE
Issues running OneDiffusion locally 

### ISSUE THREAD

**Issue by sambowenhughes** [bentoml/OneDiffusion#22]
Apple Macbook Pro M1
Sonoma 14.0
pip: 24.0
python: 3.8.6

When running `onediffusion -h` after install Im getting the following error:

```

onediffusion onediffusion -h         
Traceback (most recent call last):
  File "/Users/sam/.pyenv/versions/3.8.6/lib/python3.8/site-packages/onediffusion/utils/lazy.py", line 120, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/Users/sam/.pyenv/versions/3.8.6/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sam/.pyenv/versions/3.8.6/lib/python3.8/site-packages/onediffusion/models/stable_diffusion/configuration_stable_diffusion.py", line 23, in <module>
    class StableDiffusionConfig(onediffusion.SDConfig):
  File "/Users/sam/.pyenv/versions/3.8.6/lib/python3.8/site-packages/onediffusion/_configuration.py", line 592, in __init_subclass__
    _make_init(
TypeError: _make_init() missing 1 required positional argument: 'cls_on_setattr'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sam/.pyenv/versions/3.8.6/bin/onediffusion", line 5, in <module>
    from onediffusion.cli import cli
  File "/Users/sam/.pyenv/versions/3.8.6/lib/python3.8/site-packages/onediffusion/cli.py", line 745, in <module>
    _cached_http = {key: start_model_command(key, _context_settings=_CONTEXT_SETTINGS) for key in onediffusion.CONFIG_MAPPING}
  File "/Users/sam/.pyenv/versions/3.8.6/lib/python3.8/site-packages/onediffusion/cli.py", line 745, in <dictcomp>
    _cached_http = {key: start_model_command(key, _context_settings=_CONTEXT_SETTINGS) for key in onediffusion.CONFIG_MAPPING}
  File "/Users/sam/.pyenv/versions/3.8.6/lib/python3.8/site-packages/onediffusion/cli.py", line 522, in start_model_command
    sd_config = onediffusion.AutoConfig.for_model(model_name)
  File "/Users/sam/.pyenv/versions/3.8.6/lib/python3.8/site-packages/onediffusion/models/auto/configuration_auto.py", line 113, in for_model
    return CONFIG_MAPPING[model_name].model_construct_env(**attrs)
  File "/Users/sam/.pyenv/versions/3.8.6/lib/python3.8/site-packages/onediffusion/models/auto/configuration_auto.py", line 64, in __getitem__
    if hasattr(self._modules[module_name], value):
  File "/Users/sam/.pyenv/versions/3.8.6/lib/python3.8/site-packages/bentoml/_internal/utils/lazy_loader.py", line 70, in __getattr__
    return getattr(self._module, item)
  File "/Users/sam/.pyenv/versions/3.8.6/lib/python3.8/site-packages/onediffusion/utils/lazy.py", line 110, in __getattr__
    module = self._get_module(self._class_to_module.__getitem__(name))
  File "/Users/sam/.pyenv/versions/3.8.6/lib/python3.8/site-packages/onediffusion/utils/lazy.py", line 122, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import onediffusion.models.stable_diffusion.configuration_stable_diffusion because of the following error (look up to see its traceback):
_make_init() missing 1 required positional argument: 'cls_on_setattr'


```

**Comment by ErikCohenDev** [comment]
fixed by running `pip install attrs==23.1.0`
